/** Every public page. The suite fails if any of them regresses. */
export const routes = [
  "/",
  "/work",
  "/work/neon-metropolis",
  "/work/atlas-labs",
  "/work/flowstate",
  "/portfolio",
  "/labs",
  "/labs/sonic-orbit",
  "/labs/flicker-field",
  "/blog",
  "/blog/first-post",
  "/blog/expressive-motion",
  "/blog/category/process",
  "/about",
  "/team",
  "/services",
  "/capabilities",
  "/stack",
  "/open-source",
  "/contact",
  "/colophon",
  "/privacy",
  "/terms",
];
